import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Epilogue } from "next/font/google";
import "./globals.css";
import StoreProvider from "./storeProvider";
import SessionProvider from "@/components/SessionProvider";
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });
const epilogue = Epilogue({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={epilogue.className}>
        <StoreProvider>
          <SessionProvider>
            <Header>{children}</Header>
          </SessionProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
